name: Lint and Check Breaking Changes

on:
  pull_request:
    #    types: [ created ]
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Buf Init
        uses: bufbuild/buf-setup-action@v1.9.0
        with:
          version: latest
      - name: Buf Lint
        run: |
          buf lint
